### ISSUE TITLE
How to implement AuthorizationInterceptor?

### ISSUE THREAD

**Issue by lts1610** [saksdirect/route-composer#26]
I have an authorization's scenario as below:

1. The NavigationController have LoginViewController as rootViewController.
2. In the LoginViewController, the user taps on the SignUp button, the system navigates to SignUpViewController.
3. In the SignUpViewController, the user fills their's information, then he taps on the register button, if success, the system navigates to HomeViewController.

Expectation: 
HomeViewController should be pushed/presented or setAsRoot of the window after authorized.

@ekazaev  Could you provide an example of this?

**Comment by ekazaev** [comment]
You do not need any interceptor here. You have a direct action. User taps the button you call the configuration to present `SignUpViewController`. When user enters details and if it succeeds - you call the configuration to present `HomeViewController`.

**Comment by lts1610** [comment]
In my case, the AuthFlow as above is called everywhere if authState is unauthorized, HomeViewController is only one of it.

**Comment by ekazaev** [comment]
```swift 
let router = DefaultRouter()

class LoginViewController {

   @IBAction func signupTapped() {

        let screenConfiguration = StepAssembly(finder: ClassFinder<SignUpViewController, Any?>(options: .currentVisibleOnly),
                        factory: XibFactory())
                        .using(UINavigationController.push())
                        .from(SwitchAssembly()
                                // If login view controller present on the screen
                                .addCase(expecting: ClassFinder<LoginViewController,Any?>(options: .currentVisibleOnly))
                                .assemble(default: {
                                    // otherwise present modally
                                    return ContainerStepAssembly(finder: NilFinder(), factory: NavigationControllerFactory())
                                            .using(GeneralAction.presentModally())
                                            .from(GeneralStep.current())
                                            .assemble()
                                }))
                        .assemble()   

        try navigate(to: screenConfiguration, with: nil, animated: true, completion: { result in
            // do whatever you need like send a RxSwift Signal or do nothing
        })
    }
}


class SignUpViewController {

   @IBAction func signupTapped() {
    guard userInfoIsValid() else {
        showError()
        return
    }

    let screenConfiguration = StepAssembly(
                finder: ClassFinder<SignUpViewController, Any?>(options: .current, startingPoint: .root),
                factory: XibFactory())
                .using(GeneralAction.replaceRoot())
                .from(GeneralStep.root())
                .assemble()

    try navigate(to: screenConfiguration, with: nil, animated: true, completion: { result in
        // do whatever you need like send a RxSwiftSignal or do nothing
    })
}
```
Something like this. Of course it has no sense to keep config in the view controllers, but if we simplify it the code will be something like this.

**Comment by ekazaev** [comment]
Also, you can reuse LoginInterceptor for the cases where navigation is not involved at all. 
For example, lets assume you have a favourite button on the product(or whatever) screen. Only authorised user can add a product to his favourites. If user is not authorised, you have to offer him to login or signup. In this case no navigation process involved. But you can reuse `LoginInterceptor` without using a router:
```swift
@IBAction favoriteItemTapped() {
    LoginInterceptor<Void>().execute(completion: { result in
        guard result.isSuccessfull else {
            return
        }
        favoritesDataManager.addToFavorites(item: currentItedId)
    })    
}
```
Of course it would be better to wrap it in to something and reuse the logic written in `LoginInterceptor` not to expose it to the module.

**Comment by lts1610** [comment]
Great! Thank you so much. 😃
