### ISSUE TITLE
"Go to product 02" navigation

### ISSUE THREAD

**Issue by bonyadmitr** [saksdirect/route-composer#5]
"Star tab -> Go to product 02" send us to the circle tab.
Is it normal for example?

Also another case:
"Square tab -> Go to Star (logged in) -> Press to Square tab -> Go to split"
Star tab removed. Same question as above.

**Comment by ekazaev** [comment]
Yes. This is how product is configured.
It demmands to be shown inside of the circle tab, no matter where the user
currently is. This is part of the test - to test that it is possible to
demand view controller to be presented in a particular tab.

Yes. Split view controller replaces the root view controller of the window
so tab bar deallocates. It is not the route composers task to keep the
state of the tab bar. If keeping the tab is part of the business logic - it
must be implemented manually.

**Comment by bonyadmitr** [comment]
Thanks!
